In [5]:
import keras; 
print (keras.__version__)

2.7.0


In [7]:
import tensorflow as tf;
print(tf.__version__)

2.7.0


In [ ]:
#write your program to multiply a=(1 2 3 4 5) and b=(6 7 8 9 10) using tensor flow
#constants,variables,placeholders,shape,

a = tf.constant([1,2,3,4,5])
b = tf.constant([6,7,8,9,10])
  
# Printing the input tensor
print('a: ', a)
print('b: ', b)
  
# Calculating result
res = tf.math.multiply(x = a, y = b)
  
# Printing the result
print('Result: ', res)


a:  tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
b:  tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)
Result:  tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [ ]:
a=tf.Variable(a)
b=tf.Variable(b)
res1=tf.math.multiply(x=a,y=b)

print('Result: ',res1)

Result:  tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

In [ ]:
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(
    AB_concatenated.numpy()
))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]


In [ ]:
# Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{0}').format(
    AB_concatenated.numpy()
))


Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [ ]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))


Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

In [ ]:
# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                             shape = [1, 8])

print(('Tensor BEFORE reshape:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor AFTER reshape:\n{0}').format(
    reshaped_tensor.numpy()
))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


In [ ]:
# Making a tensor
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)


In [ ]:
print(('Tensor with floats:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(
    tensor_as_int.numpy()
))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
    A
))

The transposed matrix A:
[[3 1]
 [7 9]]


In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Some vector v
v = tf.constant([[5],
                 [2]])

# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


In [ ]:
# Element-wise multiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


In [ ]:
#How to make an identity matrix with tf.eye

# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(
    rows, columns
))

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(
    A_identity.numpy()
))


Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


In [ ]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(
    det_A
))

The determinant of A:
20.0


In [ ]:
 #Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                 [91, 10, 95],
                 [37, 13, 45]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(
    dot_AB
))


Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


In [ ]:
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(
    AB
))


Matrix Multiplication of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


In [ ]:
1.perform the following operations on matrix using tensor flow

print the identity matrix
fill the matrix with specified value
fill matrix with random value
convert matrix as numpy
addtion of 2 matrices
sub of 2 matrices
mul and div of 2 matrices
transpose of matrix
det of matrix
inverse of matrix
print eigen values of a matrix

2. solve quadratic equation using tensor flow

3. find the area of the triangle using tensor flow



In [ ]:
import tensorflow as tf

A1 = tf.constant([1,2,3])
B1 = tf.constant([1,2,3])
C1 = tf.add(A1, B1)
C1


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [ ]:
A1 = tf.constant([1,2,3])
B1 = tf.constant([1,2,3])
C1 = tf.subtract(A1, B1)
C1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [ ]:
A1 = tf.constant([1,2,3])
B1 = tf.constant([1,2,3])
C1=tf.multiply(A1,B1)
C1


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
A1 = tf.constant([1,2,3])
B1 = tf.constant([1,2,3])
C1=tf.divide(A1,B1)
C1


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [ ]:

a = 5
b = 6
c = 7

# calculate the semi-perimeter
s = (a + b + c) / 2

# calculate the area
area =(s*(s-a)*(s-b)*(s-c)) ** 0.5
print('The area of the triangle is %0.2f' %area)

The area of the triangle is 14.70


In [1]:
import numpy as np
random_matrix_array = np.random.randint(1,10,size=(3,4))
print(random_matrix_array)

[[9 8 2 6]
 [6 4 3 7]
 [9 9 2 5]]


In [15]:
matvalues=np.matrix('[1,2,3;4,5,6]')
matvalues.fill(3)
print(matvalues)

[[3 3 3]
 [3 3 3]]


In [9]:
A = np.array([[3, 7],
              [2, 5]])
A_inv = np.linalg.inv(A)
I = tf.matmul(A, A_inv)

print(I)

tf.Tensor(
[[ 5 -4]
 [ 3 -2]], shape=(2, 2), dtype=int64)


In [16]:
import numpy as np

a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)

print(w)
print(v)

[4. 1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [18]:
print(np.dot(a,v[:,0]))

[2.82842712 2.82842712]


In [19]:
np.dot(w[0],v[:,0])

array([2.82842712, 2.82842712])

In [20]:
print(np.allclose(np.dot(a,v[:,0]),np.dot(w[0],v[:,0])))

True


In [21]:
print(np.linalg.norm(v[:,0]))
print(np.linalg.norm(v[:,1]))

0.9999999999999999
0.9999999999999999
