In [1]:
import tensorflow as tf
#Multiplying two matrix
A1 = tf.constant([1, 2, 3, 4])
B1 = tf.constant([3, 4, 5, 5])
C1 = tf.multiply(A1, B1)
print(C1)

tf.Tensor([ 3  8 15 20], shape=(4,), dtype=int32)


In [2]:
#Subtract two matix
A1 = tf.constant([2,3,4,5])
B1 = tf.constant([4,5,6,7])
C1 = tf.subtract(A1,B1)
print(C1)

tf.Tensor([-2 -2 -2 -2], shape=(4,), dtype=int32)


In [3]:
#Adding two matrix
A1 = tf.constant([9,9,9,9])
B1 = tf.constant([4,4,4,4])
C1 = tf.add(A1,B1)
print(C1)

tf.Tensor([13 13 13 13], shape=(4,), dtype=int32)


In [4]:
# Matrix multiplication : tf.matmul
A1 = tf.constant([[2, 24], [2, 26], [2, 57]])
B1 = tf.constant([[1000], [150]])
C1 = tf.matmul(A1, B1)
print(C1)

tf.Tensor(
[[ 5600]
 [ 5900]
 [10550]], shape=(3, 1), dtype=int32)


In [5]:
#matrix sum
A1 = tf.Variable([[1,2,3],[3,2,1], [3,3,3]])
B2 = tf.reduce_sum(A1)
print(B2)

tf.Tensor(21, shape=(), dtype=int32)


In [6]:
A1 = tf.Variable([[1,2,3],[3,2,1], [3,3,3]])
B3 = tf.reduce_sum(A1, 0)
print(B3)

tf.Tensor([7 7 7], shape=(3,), dtype=int32)


In [7]:
A1 = tf.Variable([[1,1,1,1],[4,4,4,4],[5,5,5,5]])
B4 = tf.reduce_sum(A1, 1)
print(B4)

tf.Tensor([ 4 16 20], shape=(3,), dtype=int32)


In [8]:
# evaluating node3 and printing the result
print("Sum of A1 and B2 is:",print(B3))

tf.Tensor([7 7 7], shape=(3,), dtype=int32)
Sum of A1 and B2 is: None


In [9]:
# Construct one identity matrix.
tf.eye(2)
([[1., 0.], 
  [0., 1.]])


[[1.0, 0.0], [0.0, 1.0]]

In [10]:
# Construct one 2 x 3 "identity" matrix
tf.eye(2, num_columns=3)
([[ 1.,  0.,  0.],[ 0.,  1.,  0.]])

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]

In [11]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
x.numpy()

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
# sum all the elements
tf.reduce_sum(x).numpy()

6

In [13]:
# reduce along the first dimension
tf.reduce_sum(x, 0).numpy()

array([2, 2, 2])

In [14]:
# reduce along the second dimension
tf.reduce_sum(x, 1).numpy()

array([3, 3])

In [15]:
# returning the min value in the matrix
a = tf.constant([[0, 2, 3], [4, 5, 6]])
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [16]:
a = tf.constant([
  [[1, 2], [3, 4]],
  [[1, 2], [3, 4]]
])
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [17]:
# returning the max value from the matrix
a = tf.constant([[1,94,80],[2,49,90]])
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=94>

In [18]:
# return the mean value from the matrix
a = tf.constant([[2,0],[1,2.5]])
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=1.375>

In [19]:
# prod operation
x = tf.constant([[1,1,1],[9,9,9]])
tf.reduce_prod(x)

<tf.Tensor: shape=(), dtype=int32, numpy=729>

In [20]:
# Find area of triangle using tensorflow

In [21]:
import tensorflow as tf
import numpy as np

In [22]:
a = tf.constant(2, dtype = tf.float64)
b = tf.constant(4, dtype = tf.float64)
print('a: ', a)
print('b: ', b)
res = tf.math.multiply(a,b)/2
print('Result: ', res)

a:  tf.Tensor(2.0, shape=(), dtype=float64)
b:  tf.Tensor(4.0, shape=(), dtype=float64)
Result:  tf.Tensor(4.0, shape=(), dtype=float64)


In [23]:
# Find the roots of quadratic equation 

In [24]:
import tensorflow as tf
x = tf.constant(2.0)
y = tf.constant(1.0)
c = tf.constant(1.0)

In [25]:
import tensorflow as tf
h1 = tf.constant(1, name = "Deep_learning")
print(h1)

tf.Tensor(1, shape=(), dtype=int32)


In [26]:
h2 = tf.constant(1.1234, tf.float32)
print(h2)

tf.Tensor(1.1234, shape=(), dtype=float32)


In [27]:
h3 = tf.constant("Machine Learning", tf.string)
print(h3)

tf.Tensor(b'Machine Learning', shape=(), dtype=string)
